# Fuentes
font_family      Terminess Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13

# Ventana y Bordes
window_padding_width 10
adjust_line_height  110%

# Paleta Monocromática Blanco Puro (Zero Mono Light)
foreground            #000000
background            #ffffff
selection_foreground  #ffffff
selection_background  #000000

# Colores de la terminal (Casi todo negro/gris para mantener el minimalismo)
color0  #000000
color8  #555555
color1  #000000
color9  #555555
color2  #000000
color10 #555555
color3  #000000
color11 #555555
color4  #000000
color12 #555555
color5  #000000
color13 #555555
color6  #000000
color14 #555555
color7  #aaaaaa
color15 #ffffff

# Desactivar campana
enable_audio_bell no
